FROM node:22

WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y libvips-dev
# Copy only package files first
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Then copy the rest of the app
COPY . .
# Build the app
RUN npm run build
EXPOSE 3000

COPY docker-entrypoint.prod.sh .
RUN chmod +x docker-entrypoint.prod.sh

CMD ["./docker-entrypoint.prod.sh"]